#include <iostream>

using namespace std;

#define s ' '
#define m '#'

char letter[26][6][6] ={{s,s,m,m,s,s,
				   		 s,m,s,s,m,s,
				   		 m,m,m,m,m,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m},
				   	    {m,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,m,m,m,m,s},
				   	    {s,m,m,m,m,s,
				   	     m,s,s,s,s,m,
				   		 m,s,s,s,s,s,
				   		 m,s,s,s,s,s,
				   		 m,s,s,s,s,m,
				   		 s,m,m,m,m,s},
				   		{m,m,m,m,s,s,
				   		 m,s,s,s,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,m,s,
				   		 m,m,m,m,s,s},
				   		{m,m,m,m,m,m,
				   		 m,s,s,s,s,s,
				   		 m,m,m,m,m,s,
				   		 m,s,s,s,s,s,
				   		 m,s,s,s,s,s,
					   	 m,m,m,m,m,m},
				  		{m,m,m,m,m,m,
				  		 m,s,s,s,s,s,
				   		 m,m,m,m,m,s,
				   		 m,s,s,s,s,s,
				   		 m,s,s,s,s,s,
					   	 m,s,s,s,s,s},
					  	{s,m,m,m,m,s,
				 		 m,s,s,s,s,m,
				   		 m,s,s,s,s,s,
				   		 m,s,s,m,m,m,
				   		 m,s,s,s,s,m,
				   		 s,m,m,m,m,s},
					   	{m,s,s,s,s,m,
						 m,s,s,s,s,m,
				   		 m,m,m,m,m,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m},
				   		{s,m,m,m,s,s,
				   		 s,s,m,s,s,s,
				   		 s,s,m,s,s,s,
				   		 s,s,m,s,s,s,
				   		 s,s,m,s,s,s,
					   	 s,m,m,m,s,s},
						{s,s,m,m,m,s,
				   		 s,s,s,m,s,s,
				   		 s,s,s,m,s,s,
				   		 s,s,s,m,s,s,
				   		 s,m,s,m,s,s,
				   		 s,s,m,m,s,s},
				   		{m,s,s,s,s,m,
				   		 m,s,s,s,m,s,
				   		 m,m,m,m,s,s,
				   		 m,s,s,m,s,s,
					   	 m,s,s,s,m,s,
						 m,s,s,s,s,m},
				   		{s,m,s,s,s,s,
				   		 s,m,s,s,s,s,
				   		 s,m,s,s,s,s,
				   		 s,m,s,s,s,s,
				   		 s,m,s,s,s,s,
				   		 s,m,m,m,m,m},
				   		{m,s,s,s,s,m,
				   		 m,m,s,s,m,m,
				   		 m,s,m,m,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m},
				   		{m,s,s,s,s,m,
				   		 m,m,s,s,s,m,
				   		 m,s,m,s,s,m,
				   		 m,s,s,m,s,m,
				   		 m,s,s,s,m,m,
				   		 m,s,s,s,s,m},
				   		{s,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 s,m,m,m,m,s},
				   		{m,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,m,m,m,m,s,
				   		 m,s,s,s,s,s,
				   		 m,s,s,s,s,s},
				   		{s,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,m,m,s,m,
				   		 m,s,s,s,m,m,
				   		 s,m,m,m,m,s},
				   		{m,m,m,m,m,s,
				   		 m,s,s,s,s,m,
				   		 m,m,m,m,m,s,
				   		 m,s,m,s,s,s,
				   		 m,s,s,m,s,s,
				   		 m,s,s,s,m,s},
				   		{s,m,m,m,m,m,
				   		 m,s,s,s,s,s,
				   		 s,m,m,m,m,s,
				   		 s,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 s,m,m,m,m,s},
				   		{m,m,m,m,m,m,
				   		 s,s,m,m,s,s,
				   		 s,s,m,m,s,s,
				   		 s,s,m,m,s,s,
				   		 s,s,m,m,s,s,
				   		 s,s,m,m,s,s},
				   		{m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 s,m,m,m,m,s},
				   		{m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 s,m,s,s,m,s,
				   		 s,s,m,m,s,s},
				   		{m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 m,s,m,m,s,m,
				   		 m,s,m,m,s,m,
				   		 m,m,s,s,m,m},
				   		{m,s,s,s,s,m,
				   		 s,m,s,s,m,s,
				   		 s,s,m,m,s,s,
				   		 s,m,s,s,m,s,
				   		 m,s,s,s,s,m,
				   		 m,s,s,s,s,m},
				   		{m,s,s,s,s,m,
				   		 m,s,s,s,s,m,
				   		 s,m,s,s,m,s,
				   		 s,s,m,m,s,s,
				   		 s,m,s,s,s,s,
				   		 m,s,s,s,s,s},
				   		{m,m,m,m,m,m,
				   		 s,s,s,s,m,s,
				   		 s,s,s,m,s,s,
				   		 s,s,m,s,s,s,
				   		 s,m,s,s,s,s,
				   		 m,m,m,m,m,m}};

void show(int row, char lt) {
	for (int column=0; column<6; column++) {
		cout << letter[lt-97][row][column];
	}
	cout << "  ";
	return;
}

int main()
{
	string input;
	getline (cin,input);
	cout << endl << endl;
	int length = 0;
	while (input[length]!='\0') {
		length++;
	}
	for (int i=0; i<6; i++) {
		for (int j=0; j<length; j++) {
			if (input[j]==32) cout << "    ";
			else {
				show(i,input[j]);
			}
		}
		cout << endl;
	}
}